AnVatCanThoWeb/Areas/Admin/Controllers/CustomersController.cs
using AnVatCanTho.DataAccess.Data;
using AnVatCanThoWeb.Areas.Admin.Common;
using AnVatCanThoWeb.Areas.Admin.ViewModels.Common;
using AnVatCanThoWeb.Areas.Admin.ViewModels.Customers;
using AnVatCanThoWeb.Common.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AnVatCanThoWeb.Areas.Admin.Controllers;

[Area(AdminAreaName.Value)]
[Authorize(AuthenticationSchemes = ApplicationAuthenticationScheme.AdminScheme)]
public class CustomersController : Controller
{
    private readonly ApplicationDbContext _dbContext;

    public CustomersController(ApplicationDbContext dbContext)
    {
        _dbContext = dbContext;
    }

    public async Task<IActionResult> Index([FromQuery] GetAllCustomersRequest request)
    {
        const int pageSize = 10;
        var requestKeyword = request.Keyword;
        var requestPageIndex = request.PageIndex;
        var requestCurrentKeyword = request.CurrentKeyword;

        if (requestKeyword is not null)
        {
            requestPageIndex = 1;
        }
        else
        {
            requestKeyword = requestCurrentKeyword;
        }

        ViewData["CurrentKeyword"] = requestKeyword;

        var queryableCustomers = _dbContext.Customers
            .Include(x => x.Addresses)
            .AsQueryable();
        if (requestKeyword is not null)
        {
            queryableCustomers = queryableCustomers.Where(
                x => x.Username.Contains(requestKeyword)
                     || x.Email.Contains(requestKeyword)
                     || x.Email.Contains(requestKeyword)
                     || x.Tel.Contains(requestKeyword)
                     || x.DisplayName.Contains(requestKeyword));
        }

        var totalRows = await queryableCustomers.CountAsync();
        var totalPages = (int)Math.Ceiling((float)totalRows / pageSize);

        queryableCustomers = queryableCustomers
            .Skip((requestPageIndex - 1) * pageSize)
            .Take(pageSize);

        var customers = await queryableCustomers
            .Select(x => new CustomerViewModel
            {
                Id = x.Id,
                Dob = x.Dob,
                Email = x.Email,
                Tel = x.Tel,
                Username = x.Username,
                DisplayName = x.DisplayName,
                Addresses = x.Addresses.Select(y => new AddressViewModel(
                    y.NoAndStreet, y.DistrictName, y.WardName)),
            })
            .ToListAsync();

        var response = new GetAllCustomersResponse
        {
            Data = customers,
            TotalPages = totalPages,
            PageIndex = requestPageIndex,
        };
        return View(response);
    }

    public async Task<IActionResult> Details(int id)
    {
        var customer = await _dbContext.Customers
            .Include(x => x.Addresses)
            .FirstOrDefaultAsync(x => x.Id == id);
        if (customer is null)
        {
            return NotFound();
        }

        var customerVm = new CustomerViewModel
        {
            Id = customer.Id,
            Dob = customer.Dob,
            Email = customer.Email,
            Tel = customer.Tel,
            Username = customer.Username,
            DisplayName = customer.DisplayName,
            Avatar = customer.Avatar,
            Addresses = customer.Addresses.Select(y => new AddressViewModel(
                y.NoAndStreet, y.DistrictName, y.WardName)),
        };

        return View(customerVm);
    }

    [Route("/[area]/[controller]/details/{id:int}/orders")]
    public async Task<IActionResult> Orders([FromMultiSource] GetAllOrdersRequest request)
    {
        var customer = await _dbContext.Customers
            .FirstOrDefaultAsync(x => x.Id == request.Id);
        if (customer is null)
        {
            return NotFound();
        }

        const int pageSize = 10;

        var orders = await _dbContext.Orders
            .Include(x => x.OrderDetails)
            .ThenInclude(x => x.SnackBar)
            .Include(x => x.OrderDetails)
            .ThenInclude(x => x.Product)
            .Where(x => x.CustomerId == request.Id)
            .Skip((request.PageIndex - 1) * pageSize)
            .Take(pageSize)
            .Select(x => new OrderViewModel
            {
                Id = x.Id,
                Address = x.Address,
                Status = x.Status,
                Total = x.Total,
                OrderDetails = x.OrderDetails
                    .Select(y => new OrderDetailViewModel(
                        y.ProductId,
                        y.Product.Name,
                        y.Quantity,
                        y.Price)),
                SnackbarId = x.OrderDetails.First().SnackBarId,
                SnackbarName = x.OrderDetails.First().SnackBar.DisplayName,
            })
            .ToListAsync();

        ViewData["Customer"] = customer;
        return View(orders);
    }

    [HttpPost]
    public async Task<IActionResult> Delete([FromForm] int customerId)
    {
        var customer = await _dbContext.Customers
            .FirstOrDefaultAsync(x => x.Id == customerId);
        if (customer is null)
        {
            return NotFound();
        }

        var addresses = await _dbContext.Addresses.Where(x => x.CustomerId == customerId)
            .ToListAsync();

        try
        {
            _dbContext.Customers.Remove(customer);
            _dbContext.Addresses.RemoveRange(addresses);
            await _dbContext.SaveChangesAsync();
        }
        catch (Exception)
        {
            TempData["ErrorMessage"] = "Không thể xoá khách hàng vì liên quan đến các đơn hàng";
            return RedirectToAction("Details", new { id = customerId });
        }

        return RedirectToAction("Index");
    }
}

AnVatCanThoWeb/Areas/Admin/Controllers/SnackbarsController.cs
using AnVatCanTho.DataAccess.Data;
using AnVatCanThoWeb.Areas.Admin.Common;
using AnVatCanThoWeb.Areas.Admin.ViewModels.Common;
using AnVatCanThoWeb.Areas.Admin.ViewModels.Snackbars;
using AnVatCanThoWeb.Common.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AnVatCanThoWeb.Areas.Admin.Controllers;

[Area(AdminAreaName.Value)]
[Authorize(AuthenticationSchemes = ApplicationAuthenticationScheme.AdminScheme)]
public class SnackbarsController : Controller
{
    private readonly ApplicationDbContext _dbContext;

    public SnackbarsController(ApplicationDbContext dbContext)
    {
        _dbContext = dbContext;
    }

    public async Task<IActionResult> Index([FromQuery] GetAllSnackbarsRequest request)
    {
        const int pageSize = 10;

        var requestPageIndex = request.PageIndex;
        var requestKeyword = request.Keyword;
        var requestCurrentKeyword = request.CurrentKeyword;

        var requestDistrictName = request.DistrictName;
        var requestWardName = request.WardName;
        var requestCurrentDistrictName = request.CurrentDistrictName;
        var requestCurrentWardName = request.CurrentWardName;

        if (requestKeyword is not null
            || requestDistrictName is not null
            || requestWardName is not null)
        {
            requestPageIndex = 1;
        }

        requestKeyword ??= requestCurrentKeyword;
        requestDistrictName ??= requestCurrentDistrictName;
        requestWardName ??= requestCurrentWardName;

        ViewData["CurrentKeyword"] = requestKeyword;
        ViewData["CurrentWardName"] = requestWardName;
        ViewData["CurrentDistrictName"] = requestDistrictName;

        var snackbars = _dbContext.SnackBars
            .Include(x => x.Addresses)
            .AsQueryable();

        if (!string.IsNullOrEmpty(requestDistrictName))
        {
            snackbars = snackbars
                .Where(x => x.Addresses
                    .Any(y => y.DistrictName.Equals(requestDistrictName)));
        }

        if (!string.IsNullOrEmpty(requestWardName))
        {
            snackbars = snackbars
                .Where(x => x.Addresses
                    .Any(y => y.WardName.Equals(requestWardName)));
        }

        if (!string.IsNullOrEmpty(requestKeyword))
        {
            snackbars = snackbars
                .Where(x => x.Email.Contains(requestKeyword)
                            || x.Description.Contains(requestKeyword)
                            || x.DisplayName.Contains(requestKeyword)
                            || x.Tel.Contains(requestKeyword)
                            || x.Username.Contains(requestKeyword)
                            || x.Addresses
                                .Any(y => y.NoAndStreet.Contains(requestKeyword)));
        }

        var totalRows = await snackbars.CountAsync();
        var totalPages = (int)Math.Ceiling((float)totalRows / pageSize);

        var snackbarVms = await snackbars.Skip((requestPageIndex - 1) * pageSize)
            .Take(pageSize)
            .Select(x => new SnackbarViewModel
            {
                Id = x.Id,
                Description = x.Description,
                Dob = x.Dob,
                Email = x.Email,
                Tel = x.Tel,
                Username = x.Username,
                DisplayName = x.DisplayName,
                Addresses = x.Addresses.Select(y => new AddressViewModel(
                    y.NoAndStreet, y.DistrictName, y.WardName))
            }).ToListAsync();

        var response = new GetAllSnackbarsResponse
        {
            Data = snackbarVms,
            TotalPages = totalPages,
            PageIndex = requestPageIndex,
        };

        return View(response);
    }

    public async Task<IActionResult> Details([FromRoute] int id)
    {
        var snackbar = await _dbContext.SnackBars
            .Include(x => x.Addresses)
            .FirstOrDefaultAsync(x => x.Id == id);
        if (snackbar is null)
        {
            return NotFound();
        }

        var snackbarViewModel = new SnackbarViewModel
        {
            Id = snackbar.Id,
            Description = snackbar.Description,
            Avatar = snackbar.Avatar,
            CoverImage = snackbar.CoverImage,
            Dob = snackbar.Dob,
            Email = snackbar.Email,
            Tel = snackbar.Tel,
            Username = snackbar.Username,
            DisplayName = snackbar.DisplayName,
            Addresses = snackbar.Addresses.Select(y => new AddressViewModel(
                y.NoAndStreet, y.DistrictName, y.WardName))
        };

        return View(snackbarViewModel);
    }

    [HttpPost]
    public async Task<IActionResult> Delete([FromForm] int snackbarId)
    {
        var snackbar = await _dbContext.SnackBars
            .FirstOrDefaultAsync(x => x.Id == snackbarId);
        if (snackbar is null)
        {
            return NotFound();
        }

        var addresses = await _dbContext.Addresses
            .Where(x => x.SnackBarId == snackbarId).ToListAsync();
        
        try
        {
            _dbContext.SnackBars.Remove(snackbar);
            _dbContext.Addresses.RemoveRange(addresses);
            await _dbContext.SaveChangesAsync();
        }
        catch (Exception)
        {
            TempData["ErrorMessage"] = "Không thể xoá quầy vì liên quan đến các đơn hàng";
            return RedirectToAction("Details", new { id = snackbarId });
        }
        
        return RedirectToAction("Index");
    }

    [Route("/[area]/[controller]/details/{id:int}/products")]
    public async Task<IActionResult> Products([FromRoute] int id)
    {
        var snackbar = await _dbContext.SnackBars
            .FirstOrDefaultAsync(x => x.Id == id);
        if (snackbar is null)
        {
            return NotFound();
        }

        ViewData["Snackbar"] = snackbar;
        var products = await _dbContext.Products
            .Include(x => x.ProductCategory)
            .ThenInclude(x => x.ProductType)
            .Where(x => x.SnackBarId == id)
            .Select(x => new ProductViewModel
            {
                Id = x.Id,
                Name = x.Name,
                Description = x.Description,
                UnitPrice = x.UnitPrice,
                Ingredient = x.Ingredient,
                Stock = x.Stock,
                ProductCategoryName = x.ProductCategory.Name,
                ProductTypeName = x.ProductCategory.ProductType.Name,
            })
            .ToListAsync();

        return View(products);
    }

    [Route("/[area]/[controller]/details/{id:int}/products/{productId:int}")]
    public async Task<IActionResult> ProductDetails(int id, int productId)
    {
        var snackbar = await _dbContext.SnackBars
            .FirstOrDefaultAsync(x => x.Id == id);
        if (snackbar is null)
        {
            return NotFound();
        }

        var product = await _dbContext.Products
            .Include(x => x.ProductImages)
            .Include(x => x.ProductCategory)
            .ThenInclude(x => x.ProductType)
            .FirstOrDefaultAsync(x => x.Id == productId && x.SnackBarId == id);
        if (product is null)
        {
            return NotFound();
        }

        var productDetails = new ProductDetailsViewModel
        {
            Id = product.Id,
            Name = product.Name,
            Description = product.Description,
            UnitPrice = product.UnitPrice,
            Ingredient = product.Ingredient,
            Stock = product.Stock,
            ProductCategoryName = product.ProductCategory.Name,
            ProductTypeName = product.ProductCategory.ProductType.Name,
            ProductImages = product.ProductImages.Select(x => x.PathName)
        };

        ViewData["Snackbar"] = snackbar;

        return View(productDetails);
    }

    [HttpPost]
    public async Task<IActionResult> DeleteProduct([FromForm] int snackbarId, [FromForm] int productId)
    {
        var product = await _dbContext.Products
            .FirstOrDefaultAsync(x => x.Id == productId);
        if (product is null)
        {
            return NotFound();
        }

        var comments = await _dbContext.Comments.Where(x => x.SnackBarId == snackbarId)
            .ToListAsync();

        try
        {
            _dbContext.Comments.RemoveRange(comments);
            _dbContext.Products.Remove(product);
            await _dbContext.SaveChangesAsync();
        }
        catch (Exception)
        {
            TempData["ErrorMessage"] = "Không thể xoá sản phẩm vì liên quan đến các đơn hàng, bình luận và đánh giá";
            return RedirectToAction("ProductDetails", new { id = snackbarId, productId });
        }

        return RedirectToAction(actionName: "Products", routeValues: new { id = snackbarId });
    }
    
    [Route("/[area]/[controller]/details/{id:int}/orders")]
    public async Task<IActionResult> Orders([FromMultiSource] GetAllOrdersRequest request)
    {
        var snackbar = await _dbContext.SnackBars
            .FirstOrDefaultAsync(x => x.Id == request.Id);
        if (snackbar is null)
        {
            return NotFound();
        }

        const int pageSize = 10;
        
        var orders = await _dbContext.Orders
            .Include(x => x.OrderDetails)
            .ThenInclude(x => x.Product)
            .Where(x => x.OrderDetails
                .Any(y => y.SnackBarId == request.Id))
            .Skip((request.PageIndex - 1) * pageSize)
            .Take(pageSize)
            .Select(x => new OrderViewModel
            {
                Id = x.Id,
                Address = x.Address,
                Status = x.Status,
                Total = x.Total,
                OrderDetails = x.OrderDetails
                    .Select(y => new OrderDetailViewModel(
                        y.ProductId,
                        y.Product.Name,
                        y.Quantity, 

AnVatCanThoWeb/Areas/SnackBar/Controllers/OrderController.cs
using AnVatCanTho.DataAccess.Data;
using AnVatCanTho.Models;
using AnVatCanThoWeb.Areas.SnackBar.Common;

using AnVatCanThoWeb.Common.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;

namespace AnVatCanThoWeb.Areas.SnackBar.Controllers;

[Area(SnackbarAreaName.VALUE)]
[Authorize(AuthenticationSchemes = ApplicationAuthenticationScheme.SnackBarScheme)]
public class OrderController : Controller
{
    private readonly ApplicationDbContext _db;
    public OrderController(ApplicationDbContext db)
    {
        _db = db;
    }
    [HttpGet]
    public async Task<IActionResult> Index()
    {
        var SnackBarId = User.FindFirst(ClaimTypes.Sid);
        if (SnackBarId == null || !int.TryParse(SnackBarId.Value, out int snackBarId))
        {
            return BadRequest("ID người dùng không hợp lệ.");
        }
        var OrderId = await _db.OrderDetails.Where(od => od.SnackBarId == snackBarId).Select(od => od.OrderId).ToListAsync();

        var Orders = await _db.Orders.Include(o => o.Customer).Where(o => OrderId.Contains(o.Id)).ToListAsync();
        return View(Orders);
    }
    public async Task<IActionResult> OrderDetail(int Id)
    {
        var OrderDetail = await _db.OrderDetails.Include(od => od.Product).Where(od => od.OrderId == Id).ToListAsync();
        Order order = _db.Orders.FirstOrDefault(o => o.Id == Id);

        ViewBag.OrderStatus = order.Status; 
        return View(OrderDetail);
    }

    public async Task<IActionResult> Process(int id)
    {
        if(id == 0)
        {
            return NotFound();
        }

        Order foundOrder = _db.Orders.FirstOrDefault(o => o.Id == id);
        if(foundOrder is null)
        {
            return NotFound();
        }

        foundOrder.Status = true;
        _db.Update(foundOrder);
        _db.SaveChanges();

        return RedirectToAction("Index");
    }
}

AnVatCanThoWeb/Areas/Admin/Views/Customers/Details.cshtml
@model AnVatCanThoWeb.Areas.Admin.ViewModels.Customers.CustomerViewModel

<h1 class="mt-4">Chi tiết khách hàng</h1>
<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item">
        <a asp-action="Index" asp-controller="Home" asp-area="Admin">Trang chủ</a>
    </li>
    <li class="breadcrumb-item">
        <a asp-action="Index" asp-controller="Customers" asp-area="Admin">Khách hàng</a>
    </li>
    <li class="breadcrumb-item active">@Model.DisplayName</li>
</ol>

<div class="card mb-4">
    <div class="card-body">
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link active" href="#">
                    Thông tin tổng quan
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-action="Orders" asp-route-id="@Model.Id">Đơn hàng</a>
            </li>
        </ul>
    </div>
</div>

<div class="card mb-4">
    <div class="card-header">
        <div class="d-flex justify-content-between align-items-center">
            <a class="btn btn-outline-danger" asp-action="Index">
                <i class="fa-solid fa-angle-left"></i>
                Trở về
            </a>

            <form onsubmit="deleteProduct(event,this)" method="post" asp-action="Delete">
                <input type="hidden" name="customerId" value="@Model.Id">
                <button class="btn btn-danger">
                    <i class="fa-solid fa-trash"></i>
                </button>
            </form>
        </div>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-12 col-md-4 col-lg-3">
                <div class="flex flex-column">
                    <div class="bg-light rounded-2 border border-primary d-flex flex-column align-items-center w-100 py-5">
                        <div class="rounded-circle avatar"
                             style='background-image: url("@Url.Content($"~/images/User/{Model.Avatar}")")'>
                        </div>

                        <h5 class="text-primary mb-0">
                            @Model.DisplayName
                        </h5>

                        <span class="form-text">
                            @Html.Raw("@")@Model.Username
                        </span>
                    </div>

                    <div class="bg-light rounded-2 border border-primary d-flex flex-column align-items-center w-100 py-2 px-3 my-4">
                        <span class="text-primary form-text w-100" style="font-weight: 500">
                            Địa chỉ
                        </span>

                        <ul class="list-group list-group-flush w-100">
                            @foreach (var addr in Model.Addresses)
                            {
                                <li class="list-group-item bg-light">
                                    @addr.NoAndStreet, @addr.WardName, @addr.DistrictName
                                </li>
                            }
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-12 col-md-8 col-lg-9">
                <div class="d-flex flex-column">
                    <div class="bg-light rounded-2 border border-primary d-flex flex-column align-items-center w-100 py-2 px-3 mb-4">
                        <span class="text-primary form-text w-100" style="font-weight: 500">
                            Thông tin khách hàng
                        </span>

                        <div class="w-100 mt-1 px-2">
                            <table class="table">
                                <tbody>
                                <tr>
                                    <th>Email</th>
                                    <td>@Model.Email</td>
                                </tr>

                                <tr>
                                    <th>Số điện thoại</th>
                                    <td>@Model.Tel</td>
                                </tr>

                                <tr>
                                    <th>Ngày sinh</th>
                                    <td>@Model.Dob.ToString("dd/MM/yyyy")</td>
                                </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>

                    <div class="bg-light rounded-2 border border-primary d-flex flex-column align-items-center w-100 py-2 px-3 mb-4">
                        <span class="text-primary form-text w-100" style="font-weight: 500">
                            Đơn hàng đã đặt
                        </span>

                        <a asp-action="Orders" asp-route-id="@Model.Id" class="text-decoration-underline text-primary mt-1 mb-3">
                            Xem đơn hàng
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Styles {
    <link rel="stylesheet" href="~/console/admin/customers/details.css">
}

@section Scripts
{
    <script>
        let errorMessage = '';
        @if (TempData["ErrorMessage"] is not null)
        {
            @Html.Raw($"errorMessage = '{TempData["ErrorMessage"]!.ToString()}'")
        }
    </script>
    <script src="~/console/admin/customers/details.js"></script>
}

AnVatCanThoWeb/Areas/Admin/Views/Customers/Orders.cshtml
@model IEnumerable<AnVatCanThoWeb.Areas.Admin.ViewModels.Customers.OrderViewModel>

@{
    var customer = (ViewData["Customer"] as Customer)!;
}
<h1 class="mt-4">Thông tin đơn hàng quầy đồ ăn vặt</h1>
<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item">
        <a asp-action="Index" asp-controller="Home" asp-area="Admin">Trang chủ</a>
    </li>
    <li class="breadcrumb-item">
        <a asp-action="Index" asp-controller="Snackbars" asp-area="Admin">Khách hàng</a>
    </li>
    <li class="breadcrumb-item active">@customer.DisplayName</li>
</ol>

<div class="card mb-4">
    <div class="card-body">
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link" asp-action="Details" asp-route-id="@customer.Id">
                    Thông tin tổng quan
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" href="#">Đơn hàng</a>
            </li>
        </ul>
    </div>
</div>

<div class="card mb-4">
    <div class="card-header">
        <a class="btn btn-outline-danger" asp-action="Index">
            <i class="fa-solid fa-angle-left"></i>
            Trở về
        </a>
    </div>
    <div class="card-body">
        <div class="d-flex flex-column">
            @if (!Model.Any())
            {
                <div class="d-flex justify-content-center text-primary fw-semibold">
                    Không có đơn hàng nào
                </div>
            }
            @foreach (var order in Model)
            {
                <div class="card mb-2">
                    <div class="card-header">
                        <h5 class="text-primary fw-bold d-flex flex-row align-items-center gap-2">
                            Đơn hàng #@order.Id
                            @if (!order.Status)
                            {
                                <span class="badge text-bg-danger" style="font-size: 11px; height: auto">
                                    Đang xử lý
                                </span>
                            }
                            else
                            {
                                <span class="badge text-bg-success" style="font-size: 11px; height: auto">
                                    Đã xử lý
                                </span>
                            }
                        </h5>
                    </div>
                    <div class="card-body">
                        <div class="d-flex">
                            <span class="text-primary fw-semibold">
                                Mã quầy bán:
                            </span>
                            <span class="ms-1">#@order.SnackbarId</span>

                            <span class="text-primary fw-semibold ms-3">
                                Tên quầy:
                            </span>
                            <span class="ms-1">@order.SnackbarName</span>

                            <a asp-action="Details" asp-controller="Snackbars" asp-route-id="@order.SnackbarId" class="ms-3">
                                Xem quầy
                            </a>
                        </div>

                        <div class="d-flex mb-2">
                            <span class="text-primary fw-semibold">
                                Địa chỉ giao hàng:
                            </span>
                            <span class="ms-1">@order.Address</span>
                        </div>

                        <table class="dataTable display">
                            <thead>
                            <tr>
                                <th colspan="5">
                                    <span class="text-primary fw-semibold">
                                        Chi tiết đơn hàng
                                    </span>
                                </th>
                            </tr>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Tên sản phẩm</th>
                                <th scope="col">Số lượng</th>
                                <th scope="col">Đơn giá</th>
                                <th scope="col">Thành tiền</th>
                            </tr>
                            </thead>
                            <tbody>
                            @{
                                var i = 1;
                                var total = 0;
                            }
                            @foreach (var detail in order.OrderDetails)
                            {
                                var detailTotal = detail.Price * 1000 * detail.Quantity;
                                total += detailTotal;
                                <tr>
                                    <th>@i</th>
                                    <td>
                                        <a asp-action="ProductDetails" asp-controller="Snackbars" asp-area="Admin" asp-route-id="@order.SnackbarId" asp-route-productId="@detail.ProductId">
                                            @detail.ProductName
                                        </a>
                                    </td>
                                    <td>@detail.Quantity</td>
                                    <td>@((detail.Price * 1000).ToString("#,###,###,###")) VND</td>
                                    <td>@(detailTotal.ToString("#,###,###,###")) VND</td>
                                </tr>
                            }
                            </tbody>
                            <tfoot>
                            <tr>
                                <td colspan="5">
                                    <span class="d-flex justify-content-end w-100 fw-semibold">
                                        Tổng thành tiền: @(total.ToString("#,###,###,###")) VND
                                    </span>
                                </td>
                            </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            }

        </div>
    </div>
</div>

@section Styles {
    <link rel="stylesheet" href="https://cdn.datatables.net/2.0.3/css/dataTables.dataTables.css"/>
}