AnVatCanThoWeb/Controllers/ProductController.cs
using AnVatCanTho.DataAccess.Data;
using AnVatCanTho.Models;
using AnVatCanThoWeb.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Text.RegularExpressions;
using System.Text;
using PusherServer;
using Microsoft.AspNetCore.Authorization;
using AnVatCanThoWeb.Common.Authentication;
using Newtonsoft.Json;
using System.Security.Claims;

namespace AnVatCanThoWeb.Controllers
{
    [Authorize(AuthenticationSchemes = ApplicationAuthenticationScheme.UserScheme)]
    public class ProductController : Controller
    {

        private readonly ApplicationDbContext _db;

        private string ConvertToUnSign(string input)
        {
            input = input.Trim();

            for (int i = 0x20; i < 0x30; i++)
            {
                input = input.Replace(((char)i).ToString(), " ");
            }

            Regex regex = new Regex(@"\p{IsCombiningDiacriticalMarks}+");

            string str = input.Normalize(NormalizationForm.FormD);
            string str2 = regex.Replace(str, string.Empty).Replace('đ', 'd').Replace('Đ', 'D');

            while (str2.IndexOf("?") >= 0)
            {
                str2 = str2.Remove(str2.IndexOf("?"), 1);
            }

            return str2;
        }

        private double AvgRatingStar(Product product)
        {
            double sum = 0;

            foreach (var starItem in product.Ratings)
            {
                sum += starItem.Star;
            }
            return sum / product.Ratings.Count;
        }

        public ProductController(ApplicationDbContext db)
        {
            _db = db;
        }

        // GET: /product (list all product)
        [AllowAnonymous]
        public IActionResult Index(string[]? categoryFilter, string? sort, string? search, int page)
        {
            IQueryable<Product> productListQuery = _db.Products.Include(o => o.Ratings)
                .Include(p => p.SnackBar)
                .Include(p => p.ProductImages)
                .AsQueryable();
            List<ProductCategory> categoryList = _db.ProductCategories.ToList();
            List<ProductVM> productVM = new List<ProductVM>();

            const int PER_PAGE = 6;

            // Xử lý lọc sản phẩm
            if (categoryFilter.Length > 0)
            {
                productListQuery = productListQuery.Where(p => categoryFilter.Contains(p.ProductCategoryId.ToString()));
            }

            // Tìm tên của sản phẩm
            if (!string.IsNullOrEmpty(search))
            {
                string searchUnsign = ConvertToUnSign(search);

                //productListQuery = productListQuery.Where(p => ConvertToUnSign(p.Name).Contains(searchUnsign, StringComparison.CurrentCultureIgnoreCase));
                productListQuery = productListQuery.Where(delegate (Product p)
                {
                    if (ConvertToUnSign(p.Name).Contains(searchUnsign, StringComparison.CurrentCultureIgnoreCase))
                        return true;
                    else
                        return false;
                }).AsQueryable();

            }

            // Những product thỏa điều kiện
            List<Product> productList = productListQuery.ToList();

            // Thêm product vào View Model
            foreach (Product product in productList)
            {
                productVM.Add(new ProductVM()
                {
                    Product = product,
                    AvgRating = AvgRatingStar(product)
                });

            }

            // Xử lý sắp xếp sản phẩm
            if (sort == "desc")
            {
                productVM = productVM.OrderByDescending(p => p.Product.UnitPrice).ToList();
            }
            else if (sort == "best")
            {
                productVM = productVM.OrderByDescending(p => p.AvgRating).ToList();
            }
            else
            {
                productVM = productVM.OrderBy(p => p.Product.UnitPrice).ToList();
            }

            // Tổng số trang (Phân trang)
            ViewBag.TotalPage = (int)Math.Ceiling((decimal)productVM.Count / PER_PAGE);

            // Phân trang
            if (page <= 0)
            {
                page = 1;
            }

            int skipNum = PER_PAGE * (page - 1);

            productVM = productVM.Skip(skipNum).Take(PER_PAGE).ToList();

            // Hiển thị danh sách các loại sản phẩm
            ViewBag.CategoryList = categoryList;

            return View(productVM);
        }

        [AllowAnonymous]
        public IActionResult Details(int? id, int page, string sort)
        {
            const int RELATED_PRODUCT_NUMBER = 4;
            List<ProductVM> relatedProductsVM = new List<ProductVM>();
            const int PER_PAGE = 10;

            //Kiểm tra tham số của sản phẩm được truyền vào
            if (id == null)
            {
                return NotFound();
            }

            // Kiểm tra tham số phân trang
            if (page < 1)
            {
                page = 1;
            }
            // Tìm sản phẩm
            Product product = _db.Products
                .Include(p => p.ProductImages)
                .Include(p => p.Ratings)
                .Include(p => p.SnackBar)
                    .ThenInclude(s => s.Addresses)
                .FirstOrDefault(p => p.Id == id);

            // Kiểm tra xem có sản phẩm không
            if (product is null)
            {
                return NotFound();
            }

            IQueryable<Comment> commentQuery = _db.Comments.Include(c => c.Customer)
                .Where(c => c.ProductId == product.Id)
                .AsQueryable();

            commentQuery = (string.IsNullOrEmpty(sort) || sort == "desc")
                            ? commentQuery.OrderByDescending(p => p.CreatedAt)
                            : commentQuery.OrderBy(p => p.CreatedAt);

            // Chi tiết sản phẩm chính
            ProductVM productVM = new ProductVM()
            {
                Product = product,
                AvgRating = AvgRatingStar(product)
            };

            // Những sản phẩm có liên quan
            List<Product> relatedProducts = _db.Products
                .Include(p => p.Ratings)
                .Include(p => p.SnackBar)
                .Include(p => p.ProductImages)
                .Where(p => p.ProductCategoryId == product.ProductCategoryId && p.Id != product.Id)
                .Take(RELATED_PRODUCT_NUMBER)
                .ToList();
            foreach (Product relatedProduct in relatedProducts)
            {
                relatedProductsVM.Add(new ProductVM()
                {
                    Product = relatedProduct,
                    AvgRating = AvgRatingStar(relatedProduct)
                });
            }
            // Lấy ra tổng số bình luận của sản phẩm, và tổng số trang bình luận
            ViewBag.TotalComment = commentQuery.Count();
            ViewBag.TotalPage = (int)Math.Ceiling((double)commentQuery.Count() / PER_PAGE);

            // Lấy ra danh sách bình luận sau khi xử lý tất cả điều kiện
            List<Comment> commentList = commentQuery.Skip(PER_PAGE * (page - 1)).Take(PER_PAGE).ToList();

            // Dữ liệu View Model
            DetailProductVM detailProductVM = new DetailProductVM()
            {
                ProductVM = productVM,
                Comments = commentList,
                RelatedProduct = relatedProductsVM
            };

            return View(detailProductVM);
        }

        [HttpPost]
        public async Task<IActionResult> Comment(Comment comment, string CustomerDisplayName, string CustomerAvatar)
        {
            // Lấy giá trị từ appsettings.json
            var AppVar = new ConfigurationBuilder().AddJsonFile("appsettings.json").Build().GetSection("AppSettings");



            // Thêm bình luận vào DB
            _db.Comments.Add(comment);
            _db.SaveChanges();

            // pusher options
            var options = new PusherOptions();
            options.Cluster = AppVar["Pusher_Cluster"];

            // Trigger pusher
            var pusher = new Pusher(AppVar["Pusher_AppId"], AppVar["Pusher_AppKey"], AppVar["Pusher_AppSecret"], options);
            ITriggerResult result = await pusher.TriggerAsync("comments_channel", "push_comment_event", new { comment, CustomerDisplayName, CustomerAvatar });

            return Json(new { success = true });
        }

        public IActionResult Cart()
        {
            return View();
        }

        public IActionResult Order()
        {
            List<Product> cartList = new List<Product>();

            string userId = User.Claims.Where(c => c.Type == ClaimTypes.Sid).Select(c => c.Value).SingleOrDefault();
            Customer customer = _db.Customers.Include(c => c.Addresses).FirstOrDefault(c => c.Id == int.Parse(userId));
            if (HttpContext.Session.GetString("ShoppingCart") != null)
            {
                cartList = JsonConvert.DeserializeObject<List<Product>>(
                        HttpContext.Session.GetString("ShoppingCart")
                    );
            }

            OrderVM orderVM = new OrderVM()
            {
                Products = cartList,
                Customer = customer
            };
            return View(orderVM);
        }

        [HttpPost]
        public IActionResult Order(string customerAddress)
        {
            Dictionary<int, List<Product>> orders = new Dictionary<int, List<Product>>();
            Dictionary<int, int> total = new Dictionary<int, int>();

            // Lỗi khi đặt hàng nhưng không chọn địa chỉ
            if (customerAddress == "0" || string.IsNullOrEmpty(customerAddress))
            {
                TempData["Failed"] = "Vui lòng chọn địa chỉ để tiếp tục đặt hàng.";
                return RedirectToAction("Order");
            }
            // Lấy ra địa chỉ người dùng chọn

AnVatCanThoWeb/Controllers/ShopController.cs
using AnVatCanTho.DataAccess.Data;
using AnVatCanTho.Models;
using AnVatCanThoWeb.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AnVatCanThoWeb.Controllers
{
    public class ShopController : Controller
    {
        private readonly ApplicationDbContext _db;

        private double AvgRatingStar(Product product)
        {
            double sum = 0;

            foreach (var starItem in product.Ratings)
            {
                sum += starItem.Star;
            }
            return sum / product.Ratings.Count;
        }

        public ShopController(ApplicationDbContext db)
        {
            _db = db;
        }

        //public IActionResult Index()
        //{
        //    return View();
        //}

        public IActionResult Details(int id, int page)
        {
            List<ProductVM> productsVM = new List<ProductVM>();
            const int PER_PAGE = 8;

            if (id <= 0)
            {
                return NotFound();
            }
            
            if(page <= 0)
            {
                page = 1;
            }

            SnackBar snackBar = _db.SnackBars.FirstOrDefault(s => s.Id == id);

            if (snackBar is null)
            {
                return NotFound();
            }

            var productQuery = _db.Products.Include(p => p.Ratings)
                .Include(p => p.ProductImages)
                .Where(p => p.SnackBarId == id).AsQueryable();

            ViewBag.TotalPage = (int)Math.Ceiling((decimal)productQuery.Count() / PER_PAGE);
            
            List<Product> products = productQuery
                .Skip(PER_PAGE * (page - 1))
                .Take(PER_PAGE)
                .ToList();


            foreach (Product product in products)
            {
                productsVM.Add(new ProductVM()
                {
                    Product = product,
                    AvgRating = AvgRatingStar(product)
                });
            }


            DetailSnackBarVM detailProductVM = new DetailSnackBarVM()
            {
                ProductsVM = productsVM,
                SnackBar = snackBar
            };

            return View(detailProductVM);
        }
    }
}

AnVatCanThoWeb/Views/Shop/Details.cshtml
@using AnVatCanTho.Models
@using AnVatCanThoWeb.ViewModels
@{
    ViewData["Title"] = "Chi tiết quầy ăn";

    List<ProductVM> products = Model.ProductsVM;
    SnackBar snackBar = Model.SnackBar;

    int totalPage = ViewBag.TotalPage;
    string queryPage = Context.Request.Query["page"];
    int curPage = 1;

    if (!string.IsNullOrEmpty(queryPage))
    {
        _ = int.TryParse(queryPage, out curPage);
    }
}

@model DetailSnackBarVM

<div style="margin-top: -2px;" class="container-xxl bg-white p-0">
    <!-- Navbar & Hero Start -->
    <div class="container-xxl position-relative p-0">
        <div class="container-xxl py-5 bg-dark hero-header mb-5">
            <div class="container text-center my-5 pt-5 pb-4">
                <h1 class="display-3 text-white mb-3 animated slideInDown font-roboto">Quán ăn vặt</h1>
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb justify-content-center text-uppercase">
                        <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Home">Trang chủ</a></li>
                        <li class="breadcrumb-item text-white active" aria-current="page">Chi tiết quán ăn</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
    <!-- Navbar & Hero End -->
    <!-- Menu Start -->
    <div class="container-xxl py-5">
        <div class="container">
            <div class="text-center wow fadeInUp position-relative" data-wow-delay="0.1s">
                <div style="height: 35vh">
                    <img class="cover-image-snackbar"
                         src="@Url.Content($"/images/SnackBar/{snackBar.CoverImage}")"
                         alt="Cover image of Snack Bar" />
                </div>
                <div class="avatar-image-snackbar">
                    <img src="@Url.Content($"/images/Snackbar/{snackBar.Avatar}")"
                         class="rounded-circle"
                         width="200"
                         height="200"
                         alt="Snackbar avatar" />
                    <h3 class="mt-2 mb-5 font-roboto">@snackBar.DisplayName</h3>
                </div>
            </div>
            <div class="text-center wow fadeInUp" data-wow-delay="0.1s" style="margin-top: 30vh">
                <h1 class="mb-5 font-roboto">Sản phẩm</h1>
            </div>
            <div class="tab-class text-center wow fadeInUp" data-wow-delay="0.1s">
                <div class="tab-content">
                    <div id="tab-1" class="tab-pane fade show p-0 active">
                        <div class="row g-4">
                            @if (products.Count > 0)
                            {
                                @foreach (var item in products)
                                {
                                    var productImg = item.Product.ProductImages.FirstOrDefault(p => p.ProductId == item.Product.Id);
                                    var imgPath = productImg is null ? "no-image.jpg" : productImg.PathName;

                                    <div class="col-6 col-lg-3 mb-4 text-start">
                                        <div class="card shadow rounded-3">
                                            <img src="@Url.Content($"~/images/Products/{imgPath}")" class="card-img-top product-image-height rounded-top" alt="Hình ảnh sản phẩm">

                                            <div class="card-body border-top border-gray-300">
                                                <h3 class="fs-5 fw-bold">@item.Product.Name</h3>
                                                <a asp-action="Details" asp-controller="Shop" asp-route-id="@snackBar.Id" class="h6 fw-bold">@snackBar.DisplayName</a>
                                                <h5 class="text-gray mt-2 product-truncate-text font-roboto fs-6">@item.Product.Description</h5>
                                                <div>
                                                    <span class="h6 mb-0 text-decoration-line-through me-2 text-gray">
                                                        @(((item.Product.UnitPrice + new Random().Next(50, 99)) * 1000).ToString("#,###")) đ
                                                    </span>
                                                    @* Cần xử lý giá giảm ở đây, hiện tại chỉ hiển thị tạm *@
                                                    <span class="h5 mb-0 text-danger">@((item.Product.UnitPrice * 1000).ToString("#,###")) đ</span>
                                                </div>
                                                <div class="d-flex mt-3">
                                                    @{
                                                        int numberOfStar = (int)item.AvgRating;
                                                    }
                                                    @for (int i = 1; i <= 5; i++)
                                                    {
                                                        if (i <= numberOfStar)
                                                        {
                                                            <span class="star fas fa-star text-warning me-1"></span>
                                                        }
                                                        else
                                                        {
                                                            <span class="star fas fa-star text-gray me-1"></span>
                                                        }
                                                    }

                                                    <span class="badge ms-2 text-dark-gray">@(item.AvgRating > 0 ? (int)item.AvgRating : 0)</span>
                                                </div>

                                            </div>
                                            <div class="card-footer bg-gray-200 border-top border-gray-300 p-4">
                                                <div class="d-flex align-items-center">
                                                    <div class="me-auto">
                                                        <button onClick="AddToCart(@item.Product.Id, false, '%2FShop%2FDetails%2F' + @snackBar.Id)" class="btn product-cart-btn px-1 fs-4" id="cart_icon_@item.Product.Id" type="button" aria-label="Thêm vào giỏ hàng" title="Thêm vào giỏ hàng">
                                                            <i class="fas fa-cart-plus"></i>
                                                        </button>
                                                    </div>
                                                    <a class="btn btn-success rounded-3" asp-action="Details" asp-controller="Product" asp-route-id="@item.Product.Id">Chi tiết</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                }
                            }
                            else
                            {
                                <p class="text-muted text-center fsborder-4 fw-4">Không có sản phẩm nào</p>
                            }
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col">
                    <nav aria-label="Page navigation">
                        <ul class="pagination justify-content-center">
                            <li class="page-item @(curPage <= 1 ? "disabled" : "")"
                                onclick="PrevPage(@totalPage)">
                                <button class="page-link" @(curPage <= 1 ? "disabled" : "")>
                                    Trang trước
                                </button>
                            </li>

                            @for (int i = 1; i <= totalPage; i++)
                            {
                                <li class="page-item @(curPage == i ? "active" : "")" onclick="SpecificPage(@i)">
                                    <button class="page-link">
                                        @i
                                    </button>
                                </li>
                            }

                            <li class="page-item @(curPage >= totalPage ? "disabled" : "")"
                                onclick="NextPage(@totalPage)">
                                <button class="page-link" @(curPage >= totalPage ? "disabled" : "")>
                                    Trang sau
                                </button>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>
    <!-- Menu End -->
</div>


@section Styles {
    <link rel="stylesheet" href="~/css/product.css" asp-append-version="true"></link>
    <link rel="stylesheet" href="~/css/detail-snackbar.css" asp-append-version="true"></link>
}

@section Scripts {
    <script src="~/js/product.js"></script>
}