AnVatCanThoWeb/Areas/SnackBar/Controllers/OrderController.cs
using AnVatCanTho.DataAccess.Data;
using AnVatCanTho.Models;
using AnVatCanThoWeb.Areas.SnackBar.Common;

using AnVatCanThoWeb.Common.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;

namespace AnVatCanThoWeb.Areas.SnackBar.Controllers;

[Area(SnackbarAreaName.VALUE)]
[Authorize(AuthenticationSchemes = ApplicationAuthenticationScheme.SnackBarScheme)]
public class OrderController : Controller
{
    private readonly ApplicationDbContext _db;
    public OrderController(ApplicationDbContext db)
    {
        _db = db;
    }
    [HttpGet]
    public async Task<IActionResult> Index()
    {
        var SnackBarId = User.FindFirst(ClaimTypes.Sid);
        if (SnackBarId == null || !int.TryParse(SnackBarId.Value, out int snackBarId))
        {
            return BadRequest("ID người dùng không hợp lệ.");
        }
        var OrderId = await _db.OrderDetails.Where(od => od.SnackBarId == snackBarId).Select(od => od.OrderId).ToListAsync();

        var Orders = await _db.Orders.Include(o => o.Customer).Where(o => OrderId.Contains(o.Id)).ToListAsync();
        return View(Orders);
    }
    public async Task<IActionResult> OrderDetail(int Id)
    {
        var OrderDetail = await _db.OrderDetails.Include(od => od.Product).Where(od => od.OrderId == Id).ToListAsync();
        Order order = _db.Orders.FirstOrDefault(o => o.Id == Id);

        ViewBag.OrderStatus = order.Status; 
        return View(OrderDetail);
    }

    public async Task<IActionResult> Process(int id)
    {
        if(id == 0)
        {
            return NotFound();
        }

        Order foundOrder = _db.Orders.FirstOrDefault(o => o.Id == id);
        if(foundOrder is null)
        {
            return NotFound();
        }

        foundOrder.Status = true;
        _db.Update(foundOrder);
        _db.SaveChanges();

        return RedirectToAction("Index");
    }
}

AnVatCanThoWeb/Areas/SnackBar/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Mvc;
using AnVatCanThoWeb.Areas.SnackBar.Common;
using AnVatCanTho.DataAccess.Data;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using AnVatCanThoWeb.Common.Authentication;
using System.Security.Claims;
using AnVatCanTho.Models;
using System.Text.RegularExpressions;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using AnVatCanThoWeb.Areas.SnackBar.ViewModels.Product;

namespace AnVatCanThoWeb.Areas.SnackBar.Controllers;

[Authorize(AuthenticationSchemes = ApplicationAuthenticationScheme.SnackBarScheme)]
[Area(SnackbarAreaName.VALUE)]
public class ProductsController : Controller
{

    private readonly ApplicationDbContext _dbContext;
    private readonly IWebHostEnvironment _env;
    public ProductsController(ApplicationDbContext dbContext, IWebHostEnvironment env)
    {
        _dbContext = dbContext;
        _env = env;
    }
    //Random chuoi ki tu
    private static Random random = new Random();
    private const string chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";

    public static string GenerateRandomString(int length)
    {
        return new string(Enumerable.Repeat(chars, length)
            .Select(s => s[random.Next(s.Length)]).ToArray());
    }
    public async Task<IActionResult> Index()
    {
        int userId = int.Parse(User.Claims.First(c => c.Type == ClaimTypes.Sid).Value);
        var products = await _dbContext.Products
            .Where(s => s.SnackBar.Id == userId)
            .Include(p => p.ProductCategory)
            .ToListAsync();
        return View(products);
    }
    public async Task<IActionResult> CreateProduct()
    {
        var categories = await _dbContext.ProductCategories.ToListAsync();
        var selectList = categories
            .Select(x => new SelectListItem(text: x.Name, value: x.Id.ToString()));
        ViewBag.Categories = selectList;
        return View();
    }

    [HttpPost,ActionName("CreateProduct")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> CreateProduct(CreateProductViewModel vm, IFormFileCollection fileUploads, ProductImage productImage)
    {
        int userId = int.Parse(User.Claims.First(c => c.Type == ClaimTypes.Sid).Value);
        var categories = await _dbContext.ProductCategories.ToListAsync();
        var selectList = categories
            .Select(x => new SelectListItem(text: x.Name, value: x.Id.ToString()));
        ViewBag.Categories = selectList;
        if (ModelState.IsValid)
        {
            var product = new Product 
            {
                SnackBarId = userId,
                Stock = (int)vm.Stock,
                Name = vm.Name,
                Description = vm.Description,
                UnitPrice = (int)vm.UnitPrice,
                ProductCategoryId = vm.ProductCategoryId,
                Ingredient = vm.Ingredient
            };
            _dbContext.Products.Add(product);
            await _dbContext.SaveChangesAsync();
            if (fileUploads != null)
            {
                foreach (var fileUpload in fileUploads)
                {
                    var fileName = GenerateRandomString(10) + "-" + Path.GetFileName(fileUpload.FileName);
                    var filePath = Path.Combine(_env.WebRootPath, "images/Products", fileName);
                    if (System.IO.File.Exists(filePath))
                    {
                        ViewBag.ThongBao = "Hình ảnh đã tồn tại";
                        return View();
                    }
                    else
                    {
                        using (var stream = new FileStream(filePath, FileMode.Create))
                        {
                            fileUpload.CopyTo(stream);
                        }
                    }
                    var producimage = new ProductImage
                    {
                        SnackBarId = userId,
                        ProductId = product.Id,
                        PathName = fileName
                    };
                    _dbContext.ProductImages.Add(producimage);
                }
            }
            await _dbContext.SaveChangesAsync(); 
            return RedirectToAction(nameof(Index), product);
        }
        return View(vm);
    }

    [HttpGet]
    public async Task<IActionResult> EditProduct(int? id)
    {
        int userId = int.Parse(User.Claims.First(c => c.Type == ClaimTypes.Sid).Value);
        ViewData["snackbarid"] = userId;
        if (id == null)
        {
            return NotFound();
        }
        var categories = await _dbContext.ProductCategories.ToListAsync();
        var selectList = categories
            .Select(x => new SelectListItem(text: x.Name, value: x.Id.ToString()));
        ViewBag.Categories = selectList;
        var product = await _dbContext.Products
            .Include(p => p.SnackBar)
            .FirstOrDefaultAsync(p => p.Id == id);
        if(product == null)
        {
            return NotFound();
        }
        var vm = new CreateProductViewModel
        {
            Id = product.Id,
            Name = product.Name,
            Description = product.Description,
            Ingredient = product.Ingredient,
            ProductCategoryId = product.ProductCategoryId,
            Stock = product.Stock,
            UnitPrice = product.UnitPrice,
            SnackBarId = product.SnackBarId,
        };
        return View(vm);
    }

    [HttpPost, ActionName("EditProduct")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> EditProduct(int id, CreateProductViewModel vm)
    {
        var categories = await _dbContext.ProductCategories.ToListAsync();
        var selectList = categories
            .Select(x => new SelectListItem(text: x.Name, value: x.Id.ToString()));
        ViewBag.Categories = selectList;
        int userId = int.Parse(User.Claims.First(c => c.Type == ClaimTypes.Sid).Value);
        ViewData["snackbarid"] = userId;
        if (id != vm.Id)
        {
            return NotFound();
        }
        if (ModelState.IsValid)
        {
            try
            {
                var product = await _dbContext.Products.FirstOrDefaultAsync(x => x.Id == id);
                if (product == null) 
                {
                    return NotFound();
                }
                product.SnackBarId = userId;
                product.Description = vm.Description;
                product.Ingredient = vm.Ingredient;
                product.ProductCategoryId = vm.ProductCategoryId;
                product.Stock = (int)vm.Stock;
                product.UnitPrice = (int)vm.UnitPrice;
                product.Name = vm.Name;
                await _dbContext.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                ModelState.AddModelError("", "Error Update Data");
            }
            return RedirectToAction(nameof(Index));
        }
        return View(vm);
    }

    [HttpGet]    
    public async Task<ActionResult> DetailsAsync(int? id)
    {
        if(id == null)
        {
            return NotFound();
        }
        var viewModel = await _dbContext.Products
            .Include(s => s.ProductCategory)
            .Include(n => n.SnackBar)
            .Include(c => c.ProductImages)
            .Where(p => p.Id == id)
            .SingleOrDefaultAsync();
        if(viewModel == null)
        {
            return NotFound();
        }
        return View(viewModel);
    }
    [HttpGet]
    public async Task<ActionResult> Delete(int id)
    {
        var product = await _dbContext.Products
            .Include(p => p.ProductCategory)
            .SingleOrDefaultAsync(p => p.Id == id);
        if(product == null)
        {
            Response.StatusCode = 404;
            return null;
        }
        return View(product);
    }

    [HttpPost, ActionName("Delete")]
    public async Task<ActionResult> DeleteConfirm(int id)
    {
        var product = await _dbContext.Products
            .SingleOrDefaultAsync(p => p.Id ==id);
        if (product == null)
        {
            Response.StatusCode = 404;
            return null;
        }
        int userId = int.Parse(User.Claims.First(c => c.Type == ClaimTypes.Sid).Value);
        var producimages = await _dbContext.ProductImages
            .Where(p => p.SnackBarId == userId && p.ProductId == id)
            .ToListAsync();
        var productImages = product.ProductImages;
        foreach (var producImage in productImages) {
            string filePath = Path.Combine(_env.WebRootPath, "images/Products", producImage.PathName);
            if (System.IO.File.Exists(filePath))
            {
                System.IO.File.Delete(filePath);
            }
        }
        foreach(var producimage in producimages)
        {
            _dbContext.ProductImages.Remove(producimage);
            await _dbContext.SaveChangesAsync();
        }
        _dbContext.Products.Remove(product);
        await _dbContext.SaveChangesAsync();
        return RedirectToAction("Index");
    }
    [HttpGet]
    public async Task<ActionResult> EditProductImages(int id)
    {
        ViewData["id"] = id;
        if(id == null)
        {
            return NotFound();
        }
        int userId = int.Parse(User.Claims.First(c => c.Type == ClaimTypes.Sid).Value);
        var productImages = await _dbContext.ProductImages
            .Where(s => s.ProductId == id && s.SnackBarId == userId)
            .ToListAsync();
        if(productImages == null)
        {
            return NotFound();
        }
        return View(productImages);    
    }
    [HttpGet]
    public async Task<ActionResult> DeleteProductImage(string id)
    {
        var productImage = await _dbContext.ProductImages
            .SingleOrDefaultAsync(p => p.PathName == id);
        string filePath = Path.Combine(_env.WebRootPath, "images/Products", id);

AnVatCanThoWeb/Areas/SnackBar/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>SnackBar Admin</title>
    <link href="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/style.min.css" rel="stylesheet" />
    <link href="~/console/css/styles.css" rel="stylesheet" />
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
</head>
<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <!-- Navbar Brand-->
        <a class="navbar-brand ps-3" asp-area="SnackBar" asp-action="Index" asp-controller="Home">SnackBar Admin</a>
        <!-- Sidebar Toggle-->
        <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!">
            <i class="fas fa-bars"></i>
        </button>
        <!-- Navbar Search-->
        <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
            <div class="input-group">
                <input class="form-control" type="text" placeholder="Search for..." aria-label="Search for..."
                       aria-describedby="btnNavbarSearch" />
                <button class="btn btn-primary" id="btnNavbarSearch" type="button">
                    <i class="fas fa-search"></i>
                </button>
            </div>
        </form>
        <!-- Navbar-->
        <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown"
                   aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                    <li>
                        <a href="#" class="dropdown-item" data-toggle="modal" data-target="#logoutModal">Đăng xuất</a>
                    </li>
                </ul>
            </li>
        </ul>
    </nav>
    <!-- Logout Modal -->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="logoutModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="logoutModalLabel">Xác nhận đăng xuất</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    Bạn có chắc chắn muốn đăng xuất không?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Hủy</button>
                    <form asp-area="SnackBar" asp-controller="Account" asp-action="Logout" method="post">
                        <button type="submit" class="btn btn-primary">Đăng xuất</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <a class="nav-link" asp-area="SnackBar" asp-action="Index" asp-controller="Home">
                            Thông tin quán ăn
                        </a>
                        <a class="nav-link" asp-area="SnackBar" asp-action="Index" asp-controller="Products">
                            Quản lý món ăn
                        </a>
                        <a class="nav-link" asp-area="SnackBar" asp-action="Index" asp-controller="Order">
                            Quản lý đơn hàng
                        </a>
                    </div>
                </div>
                <div class="sb-sidenav-footer">
                    <div class="small">Tài khoản:</div>
                    @User.Identity.Name
                </div>
            </nav>
        </div>
        <div class="bg-light" id="layoutSidenav_content">
            <main>
                <div class="container-fluid px-4">
                    @RenderBody()
                </div>
            </main>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="~/js/site.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>