AnVatCanThoWeb/Areas/Admin/Controllers/ProductCategoriesController.cs
using AnVatCanTho.DataAccess.Data;
using AnVatCanTho.Models;
using AnVatCanThoWeb.Areas.Admin.Common;
using AnVatCanThoWeb.Areas.Admin.ViewModels.Category;
using AnVatCanThoWeb.Common.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace AnVatCanThoWeb.Areas.Admin.Controllers;

[Area(AdminAreaName.Value)]
[Authorize(AuthenticationSchemes = ApplicationAuthenticationScheme.AdminScheme)]
public class ProductCategoriesController : Controller
{
    private readonly ApplicationDbContext _dbContext;

    public ProductCategoriesController(ApplicationDbContext dbContext)
    {
        _dbContext = dbContext;
    }

    public async Task<IActionResult> Index([FromQuery] int? defaultTypeId)
    {
        var productTypes = await _dbContext.ProductTypes
            .ToListAsync();
        var selectListItems = productTypes
            .Select(x => new SelectListItem(text: x.Name, 
                value: x.Id.ToString(), 
                selected: x.Id == defaultTypeId ));
        ViewData["ProductTypes"] = selectListItems;
        return View();
    }

    [HttpGet]
    public async Task<IActionResult> Create()
    {
        ViewData["ProductTypes"] = await GetProductTypeListItems();
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Create(CategoryViewModel vm)
    {
        ViewData["ProductTypes"] = await GetProductTypeListItems();

        if (!ModelState.IsValid)
        {
            return View(vm);
        }

        if(!await _dbContext.ProductTypes.AnyAsync(x => x.Id == vm.ProductTypeId))
        {
            ModelState.AddModelError(nameof(vm.ProductTypeId), "Mã kiểu sản phẩm không tồn tại");
            return View(vm);
        }

        var newCate = new ProductCategory
        {
            ProductTypeId = vm.ProductTypeId,
            Name = vm.Name!,
            Description = vm.Description!,
        };
        await _dbContext.ProductCategories.AddAsync(newCate);
        await _dbContext.SaveChangesAsync();

        return RedirectToAction("Index", new {defaultTypeId = vm.ProductTypeId});
    }

    [HttpGet]
    public async Task<IActionResult> Edit(int id)
    {
        var category = await _dbContext.ProductCategories
            .FirstOrDefaultAsync(x => x.Id == id);
        if(category is null)
        {
            return NotFound();
        }
        
        ViewData["ProductTypes"] = await GetProductTypeListItems();

        var vm = new CategoryViewModel(
            category.ProductTypeId, 
            category.Name, 
            category.Description);

        return View(vm);
    }

    [HttpPost]
    [AutoValidateAntiforgeryToken]
    public async Task<IActionResult> Edit(int id, CategoryViewModel vm)
    {
        ViewData["ProductTypes"] = await GetProductTypeListItems();
        
        if (!ModelState.IsValid)
        {
            return View(vm);
        }
        
        var category = await _dbContext.ProductCategories
            .FirstOrDefaultAsync(x => x.Id == id);
        if (category is null || 
            !await _dbContext.ProductTypes.AnyAsync(x => x.Id == vm.ProductTypeId))
        {
            return View(vm);
        }

        category.ProductTypeId = vm.ProductTypeId;
        category.Description = vm.Description!;
        category.Name = vm.Name!;

        await _dbContext.SaveChangesAsync();
        
        return RedirectToAction("Index", new {defaultTypeId = vm.ProductTypeId});
    }
    
    [HttpPost]
    public async Task<IActionResult> Delete([FromRoute] int id)
    {
        var category = await _dbContext.ProductCategories
            .FirstOrDefaultAsync(x => x.Id == id);
        if (category is null)
        {
            return NotFound();
        }

        try
        {
            _dbContext.ProductCategories.Remove(category);
            await _dbContext.SaveChangesAsync();
        }
        catch (Exception)
        {
            TempData["ErrorMessage"] = "Vui lòng xoá các sản phẩm thuộc danh mục này";
        }
        
        return RedirectToAction("Index", new {defaultTypeId = category.ProductTypeId} );
    }
    
    [HttpGet("/[area]/api/product-types/{id:int}/product-categories")]
    public async Task<IActionResult> GetAllProductCategories(int id)
    {
        var productCategories = await _dbContext.ProductCategories
            .Where(x => x.ProductType.Id == id)
            .ToListAsync();
        return Ok(productCategories);
    }

    private async Task<IEnumerable<SelectListItem>> GetProductTypeListItems()
    {
        var productTypes = await _dbContext.ProductTypes
            .ToListAsync();
        var selectListItems = productTypes
            .Select(x => new SelectListItem(text: x.Name, value: x.Id.ToString()));
        return selectListItems;
    }
}

AnVatCanThoWeb/Areas/Admin/Views/ProductCategories/Create.cshtml
@model AnVatCanThoWeb.Areas.Admin.ViewModels.Category.CategoryViewModel;

<h1 class="mt-4">Tạo mới danh mục sản phẩm</h1>
<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item">
        <a asp-action="Index" asp-controller="Home" asp-area="Admin">Trang chủ</a>
    </li>
    <li class="breadcrumb-item">
        <a asp-action="Index" asp-controller="ProductCategories" asp-area="Admin">Danh mục sản phẩm</a>
    </li>
    <li class="breadcrumb-item active">Tạo mới</li>
</ol>

<div class="card mb-4">
    <div class="card-header">
        <a class="btn btn-outline-danger" asp-action="Index">
            <i class="fa-solid fa-angle-left"></i>
            Trở về
        </a>
    </div>
    <div class="card-body">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ProductTypeId" class="control-label">
                    Kiểu sản phẩm
                </label>
                <select asp-for="ProductTypeId" class="form-select" asp-items="@ViewData["ProductTypes"] as IEnumerable<SelectListItem>">
                </select>
                <span asp-validation-for="ProductTypeId" class="text-danger"></span>
            </div>
            <div class="form-group mt-4">
                <label asp-for="Name" class="control-label">
                    Tên danh mục sản phẩm
                </label>
                <input asp-for="Name" class="form-control"/>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group mt-4">
                <label asp-for="Description" class="control-label">
                    Mô tả danh mục sản phẩm
                </label>
                <input asp-for="Description" class="form-control"/>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group mt-4">
                <input type="submit" value="Thêm" class="btn btn-primary"/>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

AnVatCanThoWeb/Areas/Admin/Views/ProductCategories/Edit.cshtml
@model AnVatCanThoWeb.Areas.Admin.ViewModels.Category.CategoryViewModel;

<h1 class="mt-4">Chỉnh sửa danh mục sản phẩm</h1>
<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item">
        <a asp-action="Index" asp-controller="Home" asp-area="Admin">Trang chủ</a>
    </li>
    <li class="breadcrumb-item">
        <a asp-action="Index" asp-controller="ProductCategories" asp-area="Admin">Danh mục sản phẩm</a>
    </li>
    <li class="breadcrumb-item active">Chỉnh sửa @Model.Name</li>
</ol>

<div class="card mb-4">
    <div class="card-header">
        <a class="btn btn-outline-danger" asp-action="Index">
            <i class="fa-solid fa-angle-left"></i>
            Trở về
        </a>
    </div>
    <div class="card-body">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ProductTypeId" class="control-label">
                    Kiểu sản phẩm
                </label>
                <select asp-for="ProductTypeId" class="form-select" asp-items="@ViewData["ProductTypes"] as IEnumerable<SelectListItem>">
                </select>
                <span asp-validation-for="ProductTypeId" class="text-danger"></span>
            </div>
            <div class="form-group mt-4">
                <label asp-for="Name" class="control-label">
                    Tên danh mục sản phẩm
                </label>
                <input asp-for="Name" class="form-control"/>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group mt-4">
                <label asp-for="Description" class="control-label">
                    Mô tả danh mục sản phẩm
                </label>
                <input asp-for="Description" class="form-control"/>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group mt-4">
                <input type="submit" value="Sửa" class="btn btn-primary"/>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

AnVatCanThoWeb/Areas/Admin/Views/ProductCategories/Index.cshtml
<h1 class="mt-4">Danh mục sản phẩm</h1>
<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item">
        <a asp-action="Index" asp-controller="Home" asp-area="Admin">Trang chủ</a>
    </li>
    <li class="breadcrumb-item active">Danh mục sản phẩm</li>
</ol>
<div class="card mb-4">
    <div class="card-body">
        <div class="mb-2" style="max-width: 250px">
            <label for="product-types" class="form-label">
                Kiểu sản phẩm
            </label>
            <select id="product-types" class="form-select" asp-items="@ViewData["ProductTypes"] as IEnumerable<SelectListItem>">
                <option value="-1">Chọn kiểu sản phẩm</option>
            </select>
        </div>
    </div>
</div>
<div class="card mb-4">
    <div class="card-header">
        <a class="btn btn-outline-primary" asp-action="Create">
            <i class="fa-solid fa-plus"></i>
            Thêm mới
        </a>
    </div>
    <div class="card-body">
        <table id="my-datatable" class="display">
            <thead>
            <tr>
                <th>#</th>
                <th>Tên</th>
                <th>Mô tả</th>
                <th></th>
            </tr>
            </thead>
        </table>
    </div>
</div>

@section Styles {
    <link rel="stylesheet" href="https://cdn.datatables.net/2.0.3/css/dataTables.dataTables.css" />
}

@section Scripts {
    <script>
        let errorMessage = '';
        @if (TempData["ErrorMessage"] is not null)
        {
            @Html.Raw($"errorMessage = '{TempData["ErrorMessage"]!.ToString()}'")
        }
    </script>
    <script src="https://cdn.datatables.net/2.0.3/js/dataTables.js"></script>
    <script src="~/console/admin/product-categories/scripts.js"></script>
}